services:
    database:
        image: mysql:latest
        container_name: swag_labs_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - ./init-db:/docker-entrypoint-initdb.d
    
    phpmyadmin:
        image: phpmyadmin:latest
        container_name: swag_labs_phpmyadmin
        restart: always
        ports:
            - "8080:80"
        environment:
            PMA_HOST: database
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}